apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}-wordpress
            port:
              number: 80
  tls:
    - hosts:
        - {{ required "The domain value is required!" .Values.domain }}
      secretName: {{ .Values.tlsSecretName | default (printf "%s-tls" .Values.appName) }}


