apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-mariadb-config
  namespace: default
data:
  custom.cnf: |
    [mysqld]
    innodb_flush_log_at_trx_commit=0
    innodb_file_per_table=1
    innodb_buffer_pool_size=4G
    innodb_log_file_size=512M
    innodb_io_capacity=2000
    innodb_io_capacity_max=5000
    innodb_checksum_algorithm=crc32
    innodb_change_buffering=all
    performance_schema=0
    query_cache_type=1
    query_cache_limit=128K
    query_cache_size=64M
    query_cache_min_res_unit=512
    sql-mode="NO_ENGINE_SUBSTITUTION"
