apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-nginx-config
  namespace: default
data:
  default.conf: |
    server {
        listen 80;
        server_name {{ $.Values.appName }}-service;
        root /var/www/html;

        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~ /\.ht {
            deny all;
        }

        gzip on;
        gzip_types text/plain application/json application/javascript text/css;
        gzip_min_length 1000;
    }
