apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-service-account
  namespace: {{ .Release.Namespace | default "default" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.appName }}-role
  namespace: {{ .Release.Namespace | default "default" }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - "{{ .Values.appName }}-credentials"
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.appName }}-binding
  namespace: {{ .Release.Namespace | default "default" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.appName }}-service-account
    namespace: {{ .Release.Namespace | default "default" }}
roleRef:
  kind: Role
  name: {{ .Values.appName }}-role
  apiGroup: rbac.authorization.k8s.io
