apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-credentials
type: Opaque
data:
  rootPassword: {{ .Values.mariadb.rootPassword | default (randAlphaNum 16) | b64enc }}
  userPassword: {{ .Values.mariadb.password | default (randAlphaNum 16) | b64enc }}
